### ISSUE TITLE
ClusterBanksy throws error: "REAL() can only be applied to a 'numeric', not a 'NULL'"

### ISSUE THREAD

**Issue by jleechung** [prabhakarlab/Banksy#11]
`ClusterBanksy` throws error: 
```
REAL() can only be applied to a 'numeric', not a 'NULL'
```
This is due to a breaking change from the `igraph` package (version 1.5.0).
Read more here: https://cran.r-project.org/web/packages/igraph/news/news.html 

The package maintainers are working to upgrade `Banksy` for compatibility with `igraph` 1.5.0.

In the meantime, this error can be avoided by installing an older version of `igraph` (< 1.5.0):
1. Download source: https://cran.r-project.org/src/contrib/Archive/igraph/
2. Install as follows:  `install.packages('igraph_X.Y.Z.tar.gz', type='source', repos=NULL)`

**Comment by szhorvat** [comment]
This is caused by the `leidenAlg` package. If you upgrade to `leidenAlg` 1.1.0, the problem should go away.

**Comment by jleechung** [comment]
Thanks @szhorvat for the pointer! We'll set a minimum version requirement on `leidenAlg` in the next package update.
