### ISSUE TITLE
R Version Issue

### ISSUE THREAD

**Issue by calebhallinan** [prabhakarlab/Banksy#13]
Hello!

This is a great tool that I am hoping to use for my data, however I am running into an error where Banksy requires R version > 4.4. Is there any chance you would consider lowering this down to R version > 4.3? My work around has been to zip the package, manually change the requirement locally, then source it into R. However, I am running into an issue doing this on a remote drive and so it would be nice if I could download it for R version > 4.3 :)

If you have another solution to this I am happy to hear it out!

Best,
Caleb

**Comment by jleechung** [comment]
Hi @calebhallinan, thank you for your interest in Banksy! We've dropped the version requirement to `R >= 4.3.0` but you'll have to install from github with
```
remotes::install_github("prabhakarlab/Banksy")
```

**Comment by vipulsinghal02** [comment]
Closing this for now.
