### ISSUE TITLE
Question about normalization

### ISSUE THREAD

**Issue by Jieran-S** [prabhakarlab/Banksy#14]
Hi Banksy developer,

Thank you for developing this amazing method! I'm implementing your method and have a question regarding the preprocessing steps. 

In your vignette, you use lib-size normalization instead of log-normalization. I was wondering what is the reason behind it? Can I use log-normalization to substitute the lib-size normalization? Would it lead to a big difference in the final results?

Thank you!

**Comment by vipulsinghal02** [comment]
Hi Jieran, 

I think there are two answers to this. The first one comes from Moffitt et al.'s 2018 mouse hypothalamus MERFISH atlas paper (DOI: 10.1126/science.aau5324), where in the supplementary information, on page 15 (Section "Clustering of MERFISH data"), they state that: 

"MERFISH has a small false positive rate, as revealed by the small but finite frequency at which we observe the blank barcodes (figs. S9F-H, S11C). A logarithmic transform would tend to increase the weight of such false counts. To avoid this effect, we performed all clustering on the z-scores of the normalized RNA densities per cell, with the z-score calculated for individual genes across all cells, without applying a logarithmic transform."

We tend to not use log normalization, and instead we just do a library norm (the exact scale factoer doesn't really matter, you can use the median count across cells for example). 

This is just a heuristic, however, and the second more general answer is that as with most things in single cell analysis (like picking clustering resolution, or number of kNN neighbours, number of PCs, or how many HVGs to use, etc), we recommend letting biology guide you: look at known marker genes, for example. Or look at the spatial patterns of your clusters, and see if those pass basic sanity checks on the kind of spatial structures you expect. By the way, I would also recommend looking at this best practices page to guide you on what sort of normalization you might want to use: https://www.sc-best-practices.org/preprocessing_visualization/normalization.html .

**Comment by Jieran-S** [comment]
Thank you so much for the detailed answer! (Also congratulations on the BANKSY publication ytd)
