### ISSUE TITLE
missing code in multi-sample vignette page

### ISSUE THREAD

**Issue by abraham-abin13** [prabhakarlab/Banksy#19]
Hi, this seems like a great pipeline. 

I was trying to reproduce the "Multi-sample analysis (10x Visium Human DLPFC)" [vigneete](https://prabhakarlab.github.io/Banksy/articles/multi-sample.html). 

In the "Running BANKSY" section, the variable `spe_joint` is not defined earlier in the code. I think you may be missing a line in the vigneete. I tried to replace `spe_joint` with `spe_list` from the above code section but got this error: 

`spe_joint <- runBanksyUMAP(spe_list, use_agf = use_agf, lambda = lambda, seed = 1000)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘reducedDimNames’ for signature ‘"list"’`

Thank you for your time!

**Comment by jleechung** [comment]
Hi @abraham-abin13 , thanks for catching this! There's a [snippet of code](https://github.com/prabhakarlab/Banksy/blob/86b40563d8358add19bab87b5e4a740a800e4220/vignettes/multi-sample.Rmd#L134) that's not shown in the vignette - just add those lines and you should be able to run the rest of the code. We'll fix it soon.

**Comment by jleechung** [comment]
Fixed in c59f670
