### ISSUE TITLE
There is an M parameter in RunBanksy function in the analysis code but not in the manual.

### ISSUE THREAD

**Issue by yuanjiao123** [prabhakarlab/Banksy#21]
![image](https://github.com/prabhakarlab/Banksy/assets/160508212/d98e9674-f76c-4f1b-986e-4968a1cb3307)
![image](https://github.com/prabhakarlab/Banksy/assets/160508212/6a1ac585-185b-4d4d-8e8b-a637b51ab239)

**Comment by jleechung** [comment]
Hi @yuanjiao123, thanks for raising this issue. Could you re-install our fork of the SeuratWrappers package:

`remotes::install_github('jleechung/seurat-wrappers@feat-aft')`

The function documentation should be updated: https://github.com/jleechung/seurat-wrappers/blob/feat-aft/man/RunBanksy.Rd

with corresponding vignette here: https://github.com/jleechung/seurat-wrappers/blob/feat-aft/docs/banksy.md

To run BANKSY with `M=0`, you can set `use_agf=FALSE` in `RunBanksy`.
