### ISSUE TITLE
Double the features in BANKSY assay in seurat object 

### ISSUE THREAD

**Issue by alirezaah98** [prabhakarlab/Banksy#23]
Hello, 

I have been running the banksy on seurat object and we have a limited number of features in the dataset , we chose to run it on all the features. After running the algorithm , it doubles the features with adding ".m0" to each gene name and also it makes to be repeated in the downstream with finding marker genes. It would be great if you could explain why this thing heppens?

Thanks

**Comment by jleechung** [comment]
Hi @alirezaah98, BANKSY uses a feature augmentation approach for capturing spatial information. The additional features `m0` correspond to the mean expression in the local neighbourhood - see [Figure 1a of the paper](https://www.nature.com/articles/s41588-024-01664-3#Sec2). 

To find markers within the original gene set after running BANKSY clustering, set the default assay to `RNA` before running `FindMarkers` - see [the vignette here please](https://github.com/jleechung/seurat-wrappers/blob/fd580b24aef92ac7b101c3aeb0e3c2ba537e1b69/docs/banksy.Rmd#L183).
