### ISSUE TITLE
Multi sample analysis on seurat object

### ISSUE THREAD

**Issue by alirezaah98** [prabhakarlab/Banksy#25]
Hello there, 

I have been using  BANKSY for each sample  separately on Xenium data but I was wondering if there was a way to do the multisample analysis on seurat object as well or not? by converting it to Spatialexperiment object, it completely ruins the spatial plot and all the clusters we get, are distorted and don't show any spatial pattern , at all. Thanks

**Comment by jleechung** [comment]
Hi @alirezaah98, we've just implemented multi-sample analysis for Seurat. Please reinstall with
```
remotes::install_github('jleechung/seurat-wrappers@feat-aft')
```
and see [here](https://github.com/jleechung/seurat-wrappers/blob/feat-aft/docs/banksy.md#multi-sample-analysis) for how to run multi-sample analysis. I'm not sure if switching from SpatialExperiment to Seurat will solve your issue however. If you can share your analysis code and `sessionInfo` that would be helpful

**Comment by vipulsinghal02** [comment]
Closing this for now. @alirezaah98 feel free to reopen it if if you still need help (and would like to share your code / sessioninfo).
