### ISSUE TITLE
Typo in smoothLabels documentation example

### ISSUE THREAD

**Issue by cindyfang70** [prabhakarlab/Banksy#29]
Hi Banksy team! 

Thank you so much for this awesome package, it has been really useful in my projects. I wanted to ask about a small problem I noticed in the documentation of `smoothLabels`. Namely, in the examples the call to the function is as follows: 
`spe <- smoothLabels(spe, cluster_names = "clust_M1_lam0.2_k50_res1")`

However, I have noticed that when I follow this example I end up getting the following error: 

```
Iteration 1
Change: NA
Error in if (change == 0) { : missing value where TRUE/FALSE needed
```
I was able to resolve this by instead running `spe <- smoothLabels(spe, cluster_names = c("clust_M1_lam0.2_k50_res1"))`. 

In the documentation detailing the inputs to the function you have specified that it should be a string vector, so perhaps this is just a typo! Either way, I wanted to let you know in case it comes up again in the future and also thank you all for this great package! 

Best,
Cindy

**Comment by vipulsinghal02** [comment]
Hi Cindy, thanks for sending this message. We tried recreating the error you described, but were not able to. Just providing the string as specified in the documentation seems to work fine on our end.. 

Would you be able to share a minimum reproducible example or even just your script, along with your `sessionInfo()` with us? 

Cheers, 
Vipul

**Comment by cindyfang70** [comment]
Hi Vipul, 

Thanks so much for your quick response! I apologize for the confusion, I realized that it was not a problem with using the string vs. string vector, but rather a problem of not coercing my labels into numeric before running `smoothLabels`. 

Thank you for taking the time to try to recreate the error, and I'm sorry for the inconvenience! 

Cindy
