### ISSUE TITLE
prop_thres in smoothLabels

### ISSUE THREAD

**Issue by cindyfang70** [prabhakarlab/Banksy#30]
Hello again Banksy team,

I'm sorry for opening up another issue but I'm using the `smoothLabels` function and would like to change the cutoff for the neighbour proportion. I noticed that the `smoohter` function takes in `prop_thres` as an argument, but the `neighbor_props` threshold is [set at 0.5](https://github.com/prabhakarlab/Banksy/blob/f7793172e38ec14dcf12898419c00b1b35043840/R/cluster.R#L553) rather than using the `prop_thres` argument.

Please let me know if this is a misunderstanding on my part! Thank you again for the useful package and all your help! 

Best,
Cindy

**Comment by jleechung** [comment]
Hi Cindy, thanks for catching the bug! Should be fixed in the latest commit 9fd772b5482b2bc2eb01201de819b83825a5067a

**Comment by cindyfang70** [comment]
Amazing! Thanks for the swift response and commit!
