### ISSUE TITLE
Banksy on integrated samples creating sample-specific clusters

### ISSUE THREAD

**Issue by rstagnit** [prabhakarlab/Banksy#31]
Hi,

I've been running banksy on 10 integrated tumor samples, and I recently noticed that (at resolution = 0.1), I am getting a total of 10 clusters, and am getting 3 or 4 (depending on lambda) clusters that are largely sample specific. I was wondering if you had any ideas on arguments to change to see if I can avoid having clusters that are specific to one sample? I thought increasing k_geom would be a good place to start but that didn't seem to have much if any of an effect. 

Or, based on your expertise is it to be expected in this scenario, running banksy on a bunch of integrated samples, that once the PCA, Harmony, UMAP, etc. are done that sample-specific clusters would result. 

Any advice would be greatly appreciated as usual.

Best, 
R

**Comment by jleechung** [comment]
Hi @rstagnit, I presume you're running BANKSY, PCA, Harmony in that order as we discussed [here](https://github.com/prabhakarlab/Banksy/issues/27#issuecomment-2061579193). On the datasets that we've tried integration on, we observe good mixing across the samples for each cluster (see for example the UMAPs and spatial plots as a heuristic [here](https://prabhakarlab.github.io/Banksy/articles/batch-correction.html#run-harmony-on-banksys-embedding)). 

It's possible that there is larger technical variation observed in your data that what we've tested our workflow on. I would recommend trying the following:

1. Split scaling of the BANKSY matrix by sample of origin, by setting `split.scale=TRUE` in the `RunBanksy` call.  
```r
seu = RunBanksy(
    seu, lambda = 0.2, assay = 'SCT', slot = 'data', group = 'Sample', 
    dimx = 'dimx', dimy = 'dimy',  k_geom = 15, split.scale = TRUE)
```
Standardising data within samples makes the downstream embedding more amenable to Harmony batch correction. 

2. Ensuring that the feature set used is well represented across all samples. You could try experimenting with increasing the number of features used with Seurat's `SelectIntegrationFeatures`, for example.

I've tested the above with some Visium cancer data from [this study](https://www.nature.com/articles/s41467-023-40271-4) (data [here](https://figshare.com/articles/dataset/Spatial_transcriptomics_reveals_distinct_and_conserved_tumor_core_and_edge_architectures_that_predict_survival_and_targeted_therapy_response_/20304456/1)), with each sample coming from a different patient. After both split scaling and Harmony, there is improved mixing across samples for each cluster. See the tab below for the full workflow. Would be happy to know if this works for your data as well.

<details open>
<summary>Details</summary>

```r
library(Banksy)
library(Seurat)
library(SeuratWrappers)
library(harmony)
library(ggplot2)
library(cowplot)

rm(list=ls())

# Load data - change path as required
load('~/Downloads/sample_1.Robj')
load('~/Downloads/sample_2.Robj')
load('~/Downloads/sample_4.Robj')
load('~/Downloads/sample_5.Robj')
seu_list = list(sample_1, sample_2, sample_4, sample_5)

# Merge
seu = Reduce(merge, seu_list) 
feat = SelectIntegrationFeatures(seu_list, nfeatures = 2000)
VariableFeatures(seu) = feat
locs = Reduce(rbind.data.frame, lapply(seu_list, GetTissueCoordinates))
seu@meta.data = cbind(seu@meta.data, locs)
Idents(seu) = seu$sample_id.x

# BANKSY
group_name = 'sample_id.x'
dimx = 'imagerow'
dimy = 'imagecol'
seu = RunBanksy(
    seu, lambda = 0.2, assay = 'SCT', slot = 'data', 
    group = group_name, dimx = dimx, dimy = dimy,
    k_geom = 18, split.scale = TRUE)
seu = RunPCA(seu, features = rownames(seu), npcs = 20)
seu = RunHarmony(seu, group.by.vars=group_name, 
                 reduction.name='pca', reduction.save='harmony')

# Visualize embeddings: better mixing after Harmony
plot_grid(
    DimPlot(seu, reduction = 'pca'),
    DimPlot(seu, reduction = 'harmony')
)

# Cluster BANKSY-Harmony embedding
seu = FindNeighbors(seu, dims = 1:20, reduction = 'harmony')
seu = FindClusters(seu, resolution = 0.5, graph.name = 'BANKSY_snn')

# Visualize spatial clusters 
ggplot(
    seu@meta.data, 
    aes(x=staggered_sdimx, y=staggered_sdimy, col=seurat_clusters)) + 
    geom_point(size=0.75) +
    theme_classic() + 
    facet_wrap(~ sample_id.x, scales = 'free')
```

With `split.scale=FALSE`
<img width="540" alt="Screenshot 2024-05-17 at 18 34 38" src="https://github.com/prabhakarlab/Banksy/assets/65071847/31f005ca-3be9-4446-85a6-459e37571133">

With `split.scale=TRUE`
<img width="540" alt="Screenshot 2024-05-17 at 18 35 11" src="https://github.com/prabhakarlab/Banksy/assets/65071847/f4db21c0-9353-4e0c-b168-e9da6083d716">

</details>

**Comment by rstagnit** [comment]
Hi @jleechung ,

Thank you for your suggestion. setting `split.scale = T` seems to have worked similarly to how you displayed above, albeit best at a low resolution. I will play around also with changing some of the other arguments. Some of those sample specific clusters were appearing as very tiny groups of spots inside the main tumor core, with no notable differential gene expression compared to the tumor core, which was puzzling to me and why I wanted to ask about it.

Thanks,
R
