### ISSUE TITLE
RunBanksy error

### ISSUE THREAD

**Issue by Jadeapple** [prabhakarlab/Banksy#32]
I ran merge <- RunBanksy(merge, lambda = 0.2, verbose = TRUE,assay = "Spatial", slot = "data", features = "variable", k_geom = 15) and got the following error:
Error in RunBanksy(colon_merge, lambda = 0.2, verbose = TRUE, assay = "Spatial",  : 
  could not find function "RunBanksy"

I have installed seurat-wrappers that fits seurat v4 through remotes::install_github('satijalab/seurat-wrappers@community-vignette', quiet = TRUE), is there no RunBanksy?

**Comment by jleechung** [comment]
Hi @Jadeapple, unfortunately not. You'll have to install the latest seurat-wrappers v0.3.5 requiring seurat v5.
