### ISSUE TITLE
RunBanksy function issue

### ISSUE THREAD

**Issue by mvereten** [prabhakarlab/Banksy#34]
Dear Banksy team,

I've tried running the code as in a vignette provided, and I get an error related to 'compute.banksyMatrices':

ss.hippo <- RunBanksy(ss.hippo, lambda = 0.2, verbose=TRUE,  assay = 'Spatial', slot = 'data', features = 'variable', k_geom = 15)

Fetching data from slot data from assay Spatial
Subsetting by features
Computing neighbor matrix
Error in RunBanksy(ss.hippo, lambda = 0.2, verbose = TRUE, assay = "Spatial",  : 
  object 'compute.banksyMatrices' not found

Is this something that is very easy to fix, is there some extra data to load or a function to run to make this object?

Thanks,
Maria

**Comment by jleechung** [comment]
Hi Maria, this should be easily fixable. Can you refer to the discussion here:  https://github.com/prabhakarlab/Banksy/issues/26#issuecomment-2051933638? Restarting your R session, then uninstalling Banksy / SeuratWrappers and re-installing should hopefully work.

**Comment by mvereten** [comment]
Thank you very much, I've fixed it by reinstalling etc.
