### ISSUE TITLE
link to the `center = TRUE` argument

### ISSUE THREAD

**Issue by vipulsinghal02** [prabhakarlab/Banksy#37]
Currently, centering always happens in `computeBanksy`, and the center argument has no effect. Link the two things so the argument functions as expected. https://github.com/prabhakarlab/Banksy/blob/e8a479dc7d30b5728692f18e16c0be17dd6f62a8/R/computation.R#L122

**Comment by jleechung** [comment]
Thanks for the catch! Fixed in [fbb4891](https://github.com/prabhakarlab/Banksy/commit/fbb4891010f8555f64c4eb7ece14f633521699a7).
