### ISSUE TITLE
Extracting Cells IDs that were used to generate Banksy K_geom neighborhood

### ISSUE THREAD

**Issue by Alwash-317** [prabhakarlab/Banksy#40]

**Comment by vipulsinghal02** [comment]
Hi Alwash, 

did you manage to figure this out? You might want to look at this part of the code: https://github.com/prabhakarlab/Banksy/blob/fbb4891010f8555f64c4eb7ece14f633521699a7/R/computation.R#L336

Best, 
Vipul
