### ISSUE TITLE
Multi-sample integration analysis

### ISSUE THREAD

**Issue by hzongyao** [prabhakarlab/Banksy#5]
I saw in your example data that the software can achieve simultaneous analysis of multiple samples and can identify the results of inter-sample consistency clustering（https://prabhakarlab.github.io/Banksy/articles/dlpfc-analysis.html）, I would like to ask if this result can be interpreted as the integrated analysis result after removing the potential batch effect between samples? Thank you!

**Comment by hzongyao** [comment]
Thank you very much for your reply, I will read the article you recommended about the methodology of spatial correlation analysis, in short, thank you very much for the tool your team developed, it is a great job!

**Comment by vipulsinghal02** [comment]
Absolutely, glad it can be useful for you!
