### ISSUE TITLE
add the nbr matrix from bank object directly to the seurat object for subsequent analysis

### ISSUE THREAD

**Issue by hzongyao** [prabhakarlab/Banksy#6]
By studying your code, I found that we are using the Banksy::compute.banksyMatrices function to compute the nbr matrix, both for the bansky object and  seurat object using the seurat wapper，but I saw the process of add the nbr matrix to seurat object including other additional actions like from seurat wapper：
data_banksy <- Matrix::Matrix(rbind(sqrt(1 - lambda) * data_own, 
    sqrt(lambda) * data_nbr), sparse = TRUE)

I'm curious if there are any other potential problems if I add the nbr matrix from bank object directly to the seurat object for subsequent analysis ? The example code is as follows：se represents a seurat object
assay.out <- Seurat::CreateAssayObject(counts = bank@own.expr)
assay.out <- Seurat::SetAssayData(object = assay.out, slot = "data", 
                            new.data =  bank@nbr.expr) 
  se[["Banksy"]] <- assay.out
  Seurat::DefaultAssay(object = se) <- "Banksy"

**Comment by jleechung** [comment]
Hi @hzongyao 

The BANKSY matrix is the row concatenation of two matrices:

1.  Own expression matrix (`own.expr`) scaled by sqrt(1-lambda`)
2.  Neighbor matrix (`nbr.expr`) scaled by sqrt(lambda)

We compute the neighbor matrix with `ComputeBanksy` (via `compute.banksyMatrices` as you've noted), and store this matrix in the `nbr.expr` slot. Note that we only need to compute the neighbor matrix once: for different values of lambda, we can compute the BANKSY matrix (`data_banksy`) easily following the above without storing the BANKSY matrix in memory.

Hence if you'd like to perform clustering in Seurat with the BANKSY matrix, I recommend you follow issue #3.  

If you want to add the original `own.expr` or `nbr.expr` matrices to your Seurat object, you can do so in separate assays:

```r
library(Banksy)
library(Seurat)

data(hippocampus)

# Run BANKSY
bank <- BanksyObject(own.expr = hippocampus$expression, cell.locs = hippocampus$locations)
bank <- NormalizeBanksy(bank)
bank <- ComputeBanksy(bank)
bmat <- getBanksyMatrix(bank, lambda = 0.3)

# Create Seurat object
seu <- CreateSeuratObject(counts = bmat$expr, assay = 'BANKSY')
# Add own and nbr expression as separate assays
seu[['Own']] <- CreateAssayObject(counts = bank@own.expr)
seu[['Neighbor']] <- CreateAssayObject(counts = bank@nbr.expr)
```

The Seurat object now contains three assays which you can toggle between with `Seurat::DefaultAssay`
```
> print(seu)
An object of class Seurat 
480 features across 10994 samples within 3 assays 
Active assay: BANKSY (240 features, 0 variable features)
 2 other assays present: Own, Neighbor
```
