### ISSUE TITLE
Warning in `RunUMAP` with multiple lambdas and pca=FALSE

### ISSUE THREAD

**Issue by retogerber** [prabhakarlab/Banksy#7]
Hi

When I run `RunUMAP` with multiple values for lambda and and `pca=FALSE` I get the following warning:
## shorter object length
Which basically results in calculating the same UMAP for all values of lambda (i.e. it always takes the first).

Thanks,
Reto

**Comment by jleechung** [comment]
Hi @retogerber 

Thanks for pointing that out. This issue should be resolved with the latest commit.

**Comment by retogerber** [comment]
Thanks, seems to work fine now.
